### ISSUE TITLE
Render without any style

### ISSUE THREAD

**Issue by rubenbonilla** [subosito/snowboard#15]
I'm using docker to render .apib file so i'm executing something like this

`docker run --rm -it -v $PWD/doc:/doc subosito/snowboard html -i doc.apib -o output.html`

When a try to visualize the web page on chrome does not have styles.
I inspected the web page and found this: 

```
GET file://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/semantic.min.css net::ERR_FILE_NOT_FOUND
02. Resource and Actions.html:9 GET file://cdnjs.cloudflare.com/ajax/libs/prism/1.5.1/themes/prism-okaidia.min.css net::ERR_FILE_NOT_FOUND
02. Resource and Actions.html:379 GET file://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js net::ERR_FILE_NOT_FOUND
02. Resource and Actions.html:380 GET file://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/components/accordion.min.js net::ERR_FILE_NOT_FOUND
02. Resource and Actions.html:381 GET file://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/components/tab.min.js net::ERR_FILE_NOT_FOUND
02. Resource and Actions.html:382 GET file://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/components/transition.min.js net::ERR_FILE_NOT_FOUND
02. Resource and Actions.html:383 GET file://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/components/popup.min.js net::ERR_FILE_NOT_FOUND
02. Resource and Actions.html:384 GET file://cdnjs.cloudflare.com/ajax/libs/prism/1.5.1/prism.min.js net::ERR_FILE_NOT_FOUND
02. Resource and Actions.html:385 GET file://cdnjs.cloudflare.com/ajax/libs/prism/1.5.1/components/prism-json.min.js net::ERR_FILE_NOT_FOUND
02. Resource and Actions.html:387 Uncaught ReferenceError: $ is not defined
    at 02. Resource and Actions.html:387
(anonymous) @ 02. Resource and Actions.html:387
```

Does it has something to do?

**Comment by vsorkin** [comment]
This happens because generated HTML-document tries to fetch external resources without specification of the desired protocol. In this case browser chooses the same protocol which is used to access main document. You open the doc straight from the disk(file://), so the browser seeks for external resources on your local machine and doesn't find them. You have two options to  overcome this.
* Open the doc accessing it via some webserver. I.e. run php -S localhost:8000 in your doc dir. And then go to http://localhost:8000/output.html
* Prepend all occurrences of `//cdnjs` and `//ajax` with `http:`

**Comment by subosito** [comment]
I think @vsorkin answer already explain how to fix this issue. @rubenbonilla please reopen the issue if still persist.

**Comment by rubenbonilla** [comment]
Thanks you so much @vsorkin !! Now it's working perfectly.
